"""add extracted text

Revision ID: 805a757e03c1
Revises: 6552b817bcb0
Create Date: 2026-06-21 19:54:15.229027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805a757e03c1'
down_revision: Union[str, Sequence[str], None] = '6552b817bcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_documents', 'extracted_text')
    # ### end Alembic commands ###
