"""update loan document filenames

Revision ID: b48843226de6
Revises: 59831ff17a57
Create Date: 2026-06-05 19:32:19.557999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48843226de6'
down_revision: Union[str, Sequence[str], None] = '59831ff17a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_documents', sa.Column('original_file_name', sa.String(length=255), nullable=False))
    op.add_column('loan_documents', sa.Column('stored_file_name', sa.String(length=255), nullable=False))
    op.drop_column('loan_documents', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('loan_documents', 'stored_file_name')
    op.drop_column('loan_documents', 'original_file_name')
    # ### end Alembic commands ###
